prompt --application/set_environment
set define off verify off feedback off
whenever sqlerror exit sql.sqlcode rollback
--------------------------------------------------------------------------------
--
-- Oracle APEX export file
--
-- You should run this script using a SQL client connected to the database as
-- the owner (parsing schema) of the application or as a database user with the
-- APEX_ADMINISTRATOR_ROLE role.
--
-- This export file has been automatically generated. Modifying this file is not
-- supported by Oracle and can lead to unexpected application and/or instance
-- behavior now or in the future.
--
-- NOTE: Calls to apex_application_install override the defaults below.
--
--------------------------------------------------------------------------------
begin
wwv_flow_imp.import_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>1601438889569217
,p_default_application_id=>1400
,p_default_id_offset=>4009255697527821
,p_default_owner=>'FSM'
);
end;
/
 
prompt APPLICATION 1400 - FSM - Planning
--
-- Application Export:
--   Application:     1400
--   Name:            FSM - Planning
--   Exported By:     ADMIN
--   Flashback:       0
--   Export Type:     Page Export
--   Manifest
--     PAGE: 51
--   Manifest End
--   Version:         24.2.0
--   Instance ID:     743301615293412
--

begin
null;
end;
/
prompt --application/pages/delete_00051
begin
wwv_flow_imp_page.remove_page (p_flow_id=>wwv_flow.g_flow_id, p_page_id=>51);
end;
/
prompt --application/pages/page_00051
begin
wwv_flow_imp_page.create_page(
 p_id=>51
,p_name=>'Close SPIN-LOT'
,p_alias=>'CLOSE-SPIN-LOT'
,p_step_title=>'Close SPIN-LOT'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* Page 51 - Close SPIN-LOT (SC-INV700) - APEX JS (RGN_P51_JAVASCRIPT) */',
'',
'var inv700 = {',
'  filter: "OPEN",',
'  lots: [],',
'  selectedWo: null,',
'  lotData: null,',
'  phase: "idle",',
'  closingTimer: null,',
'};',
'',
'function inv700Init() {',
'  inv700BindEvents();',
'  inv700.filter = "OPEN";',
'  $("#inv700-filter-open").addClass("is-active");',
'  $("#inv700-filter-all").removeClass("is-active");',
'  inv700Search({ silent: true });',
'}',
'',
'function inv700BindEvents() {',
'  $("#inv700-btn-load").on("click", inv700Search);',
'  $("input.inv700-input#P51_SEARCH").on("keydown", function (e) {',
'    if (e.key === "Enter") inv700Search();',
'  });',
'  $("#inv700-filter-open").on("click", function () { inv700SetFilter("OPEN"); });',
'  $("#inv700-filter-all").on("click", function () { inv700SetFilter("ALL"); });',
'  $("#inv700-lot-list-body").on("click", ".inv700-lot-row", function () {',
'    inv700SelectLot($(this).data("works-order"));',
'  });',
'  $("#inv700-btn-close").on("click", inv700ConfirmClose);',
'  $("#inv700-btn-clear").on("click", inv700ClearSelection);',
'}',
'',
'function inv700Val(item) {',
'  if (item === "P51_SEARCH") {',
'    var $vis = $("input.inv700-input#P51_SEARCH");',
'    if ($vis.length) return ($vis.val() || "").trim();',
'  }',
'  return ($v(item) || "").trim();',
'}',
'',
'function inv700SetFilter(f) {',
'  inv700.filter = f;',
'  $("#inv700-filter-open, #inv700-filter-all").removeClass("is-active");',
'  $("#inv700-filter-" + f.toLowerCase()).addClass("is-active");',
'  apex.item("P51_FILTER").setValue(f);',
'  inv700Search();',
'}',
'',
'function inv700Search(opts) {',
'  opts = opts || {};',
'  var q = inv700Val("P51_SEARCH");',
'  if (q) {',
'    apex.item("P51_SEARCH").setValue(q);',
'  }',
'  apex.server.process("SEARCH_LOTS", {',
'    x01: q,',
'    x02: inv700.filter,',
'  }, {',
'    dataType: "json",',
'    success: function (data) {',
'      inv700.lots = data.lots || [];',
'      inv700RenderList();',
'      if (inv700.lots.length === 1) {',
'        inv700SelectLot(inv700.lots[0].worksOrder);',
'      } else if (inv700.lots.length === 0) {',
'        inv700ClearDetail();',
'        if (!opts.silent) {',
'          apex.message.showPageSuccess("No lots found.");',
'        }',
'      }',
'    },',
'    error: inv700AjaxError,',
'  });',
'}',
'',
'function inv700SelectLot(worksOrder) {',
'  if (!worksOrder || inv700.phase === "closing") return;',
'',
'  apex.server.process("LOAD_LOT", {',
'    x01: worksOrder,',
'  }, {',
'    dataType: "json",',
'    success: function (data) {',
'      if (!data || !data.lot) {',
'        apex.message.alert("Lot not found or not a main spin lot.");',
'        return;',
'      }',
'      inv700.selectedWo = worksOrder;',
'      inv700.lotData = data;',
'      inv700.phase = data.lot.isClosed ? "closed" : "loaded";',
'      apex.item("P51_WORKS_ORDER").setValue(worksOrder);',
'      apex.item("P51_LOT_ID").setValue(data.lot.lotId);',
'      inv700RenderList();',
'      inv700RenderDetail();',
'      inv700UpdateActionBar();',
'    },',
'    error: inv700AjaxError,',
'  });',
'}',
'',
'function inv700RenderList() {',
'  var $body = $("#inv700-lot-list-body");',
'  var $ws = $("#inv700-workspace");',
'  var n = inv700.lots.length;',
'',
'  $("#inv700-lot-count").text(n + " lot" + (n !== 1 ? "s" : ""));',
'',
'  if (n === 0) {',
'    $body.empty();',
'    $ws.removeClass("inv700-workspace--multi").addClass("inv700-workspace--empty");',
'    return;',
'  }',
'',
'  $ws.removeClass("inv700-workspace--empty");',
'  $ws.toggleClass("inv700-workspace--multi", n > 1);',
'',
'  var html = inv700.lots.map(function (row) {',
'    var sel = row.worksOrder === inv700.selectedWo ? " is-selected" : "";',
'    var stClass = row.isClosed ? "inv700-lot-row__status--ok" : "inv700-lot-row__status--sc";',
'    var st = row.isClosed ? "OK" : "SC";',
'    return (',
'      ''<button type="button" class="inv700-lot-row'' + sel + ''" data-works-order="'' +',
'      inv700Esc(row.worksOrder) + ''">'' +',
'      ''<div class="inv700-lot-row__top">'' +',
'      ''<span class="inv700-lot-row__no">'' + inv700Esc(row.worksOrder) + "</span>" +',
'      ''<span class="inv700-lot-row__status '' + stClass + ''">'' + st + "</span>" +',
'      "</div>" +',
'      ''<div class="inv700-lot-row__sub">'' +',
'      inv700Esc(row.yarnFlg) + " · " + inv700Esc(row.mcode) + " · " + inv700Esc(row.dateSch || "") +',
'      "</div></button>"',
'    );',
'  }).join("");',
'',
'  $body.html(html);',
'}',
'',
'function inv700RenderDetail() {',
'  var d = inv700.lotData;',
'  if (!d || !d.lot) {',
'    inv700ClearDetail();',
'    return;',
'  }',
'',
'  var lot = d.lot;',
'  var closed = lot.isClosed || inv700.phase === "closed";',
'',
'  $("#inv700-detail-empty").addClass("inv700-hidden");',
'  $("#inv700-detail-content").removeClass("inv700-hidden");',
'  $("#inv700-action-bar").removeClass("inv700-hidden");',
'',
'  $("#inv700-lot-no").text(lot.lotNo);',
'  $("#inv700-lot-id").text("lot_id " + lot.lotId);',
'  $("#inv700-product").text(lot.productNo);',
'  $("#inv700-yarn").text(lot.yarnFlg);',
'  $("#inv700-mcode").text(lot.mcode);',
'  $("#inv700-date-sch").text(lot.dateSch || "-");',
'  $("#inv700-qty-ord").text(inv700Fmt(lot.qtyOrd, 1));',
'  $("#inv700-qty-rec").text(inv700Fmt(lot.qtyRec));',
'  $("#inv700-qoh").text(inv700Fmt(lot.qoh));',
'  $("#inv700-kgs1").text(inv700Fmt(lot.kgs1));',
'  $("#inv700-kgs2").text(inv700Fmt(lot.kgs2));',
'',
'  var $hero = $("#inv700-lot-hero");',
'  $hero.toggleClass("is-closed", closed);',
'  $("#inv700-stamp").toggleClass("inv700-hidden", !closed);',
'',
'  inv700SetStatus(closed ? "closed" : inv700.phase === "closing" ? "closing" : "open");',
'',
'  var impact = (d.impact || []).filter(function (s) { return s.count > 0; });',
'  var total = impact.reduce(function (n, s) { return n + s.count; }, 0);',
'  $("#inv700-impact-summary").text(total + " record" + (total !== 1 ? "s" : "") + " will update");',
'',
'  var listHtml = impact.map(function (s, i) {',
'    var done = closed || (inv700.phase === "closing" && i < inv700.closingStep);',
'    return (',
'      ''<li class="inv700-impact-item'' + (done ? " is-done" : "") + ''">'' +',
'      ''<span class="inv700-impact-item__dot"></span>'' +',
'      ''<span class="inv700-impact-item__label">'' + inv700Esc(s.label) + "</span>" +',
'      ''<span class="inv700-impact-item__sub">'' + s.count + " record" + (s.count !== 1 ? "s" : "") + "</span>" +',
'      (done ? ''<span class="inv700-impact-item__done">Closed</span>'' : "") +',
'      "</li>"',
'    );',
'  }).join("");',
'  $("#inv700-impact-list").html(listHtml);',
'',
'  var pct = closed ? 100 : inv700.phase === "closing" ? (inv700.closingStep / impact.length) * 100 : 0;',
'  $("#inv700-progress").toggleClass("inv700-hidden", inv700.phase === "idle" || inv700.phase === "loaded");',
'  $("#inv700-progress-bar").css("width", pct + "%").toggleClass("is-closed", closed);',
'}',
'',
'function inv700UpdateActionBar() {',
'  var lot = inv700.lotData && inv700.lotData.lot;',
'  if (!lot) return;',
'',
'  var closed = lot.isClosed || inv700.phase === "closed";',
'  $("#inv700-action-lot").text(lot.lotNo);',
'  $("#inv700-action-msg").text(',
'    closed ? "Archived" : inv700.phase === "closing" ? "Closing in progress…" : "Ready to close"',
'  );',
'  $("#inv700-btn-close")',
'    .prop("disabled", closed || inv700.phase === "closing")',
'    .text(closed ? "Already closed" : inv700.phase === "closing" ? "Closing…" : "Close SPIN-LOT");',
'}',
'',
'function inv700SetStatus(mode) {',
'  var $p = $("#inv700-status");',
'  $p.removeClass("inv700-hidden inv700-pill--open inv700-pill--closing inv700-pill--closed");',
'  if (mode === "open") {',
'    $p.addClass("inv700-pill--open").text("Open");',
'  } else if (mode === "closing") {',
'    $p.addClass("inv700-pill--closing").text("Closing…");',
'  } else if (mode === "closed") {',
'    $p.addClass("inv700-pill--closed").text("Closed");',
'  } else {',
'    $p.addClass("inv700-hidden");',
'  }',
'}',
'',
'function inv700ConfirmClose() {',
'  var lotId = inv700Val("P51_LOT_ID");',
'  if (!lotId) return;',
'',
'  apex.message.confirm("Close this SPIN-LOT? This cannot be undone from this page.", function (ok) {',
'    if (!ok) return;',
'    inv700RunClose(lotId);',
'  });',
'}',
'',
'function inv700RunClose(lotId) {',
'  inv700.phase = "closing";',
'  inv700.closingStep = 0;',
'  var impact = (inv700.lotData.impact || []).filter(function (s) { return s.count > 0; });',
'  inv700SetStatus("closing");',
'  inv700UpdateActionBar();',
'  inv700RenderDetail();',
'',
'  var i = 0;',
'  clearInterval(inv700.closingTimer);',
'  inv700.closingTimer = setInterval(function () {',
'    i += 1;',
'    inv700.closingStep = i;',
'    inv700RenderDetail();',
'    if (i >= impact.length) {',
'      clearInterval(inv700.closingTimer);',
'    }',
'  }, 580);',
'',
'  apex.server.process("CLOSE_LOT", { x01: lotId }, {',
'    dataType: "json",',
'    success: function (data) {',
'      clearInterval(inv700.closingTimer);',
'      if (data.success) {',
'        inv700.phase = "closed";',
'        if (inv700.lotData && inv700.lotData.lot) {',
'          inv700.lotData.lot.isClosed = true;',
'        }',
'        inv700.closingStep = impact.length;',
'        inv700RenderDetail();',
'        inv700UpdateActionBar();',
'        inv700Search();',
'        apex.message.showPageSuccess(data.message || "SPIN-LOT closed.");',
'      } else {',
'        inv700.phase = "loaded";',
'        inv700RenderDetail();',
'        inv700UpdateActionBar();',
'        apex.message.alert(data.message || "Close failed.");',
'      }',
'    },',
'    error: function (xhr, status, err) {',
'      clearInterval(inv700.closingTimer);',
'      inv700.phase = "loaded";',
'      inv700RenderDetail();',
'      inv700UpdateActionBar();',
'      inv700AjaxError(xhr, status, err);',
'    },',
'  });',
'}',
'',
'function inv700ClearSelection() {',
'  inv700.selectedWo = null;',
'  inv700.lotData = null;',
'  inv700.phase = "idle";',
'  inv700ClearDetail();',
'  inv700RenderList();',
'  inv700SetStatus(null);',
'}',
'',
'function inv700ClearDetail() {',
'  $("#inv700-detail-content").addClass("inv700-hidden");',
'  $("#inv700-detail-empty").removeClass("inv700-hidden");',
'  $("#inv700-action-bar").addClass("inv700-hidden");',
'  apex.item("P51_LOT_ID").setValue("");',
'  apex.item("P51_WORKS_ORDER").setValue("");',
'}',
'',
'function inv700Fmt(n, dec) {',
'  if (n == null || n === "") return "-";',
'  var x = Number(n);',
'  if (isNaN(x)) return n;',
'  return dec ? x.toFixed(dec) : x.toLocaleString("en-US");',
'}',
'',
'function inv700Esc(s) {',
'  return String(s == null ? "" : s)',
'    .replace(/&/g, "&amp;")',
'    .replace(/</g, "&lt;")',
'    .replace(/"/g, "&quot;");',
'}',
'',
'function inv700AjaxError(xhr, status, err) {',
'  var msg = (xhr.responseJSON && xhr.responseJSON.message) || err || status || "Request failed";',
'  apex.message.alert(msg);',
'}',
'',
'apex.jQuery(function () {',
'  inv700Init();',
'});',
''
,p_inline_css=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/* =============================================================================',
'   Page 51 - Close SPIN-LOT - Light theme (maquette validée)',
'   Coller dans Page Properties → CSS → Inline (remplace tout)',
'   ============================================================================= */',
'',
':root {',
'  --inv700-bg: #f4f4f6;',
'  --inv700-surface: #ffffff;',
'  --inv700-surface-alt: #eef0f3;',
'  --inv700-bar: #ffffff;',
'  --inv700-stroke: rgba(0, 0, 0, 0.1);',
'  --inv700-text: #1c1c22;',
'  --inv700-text-muted: #6e6e7a;',
'  --inv700-accent: #2563eb;',
'  --inv700-accent-hover: #1d4ed8;',
'  --inv700-warn: #b45309;',
'  --inv700-closed: #dc2626;',
'  --inv700-info: #2563eb;',
'  --inv700-shadow: 0 1px 4px rgba(0, 0, 0, 0.08), 0 4px 16px rgba(0, 0, 0, 0.04);',
'  --inv700-radius: 8px;',
'}',
'',
'/* --- APEX shell --- */',
'body.t-PageBody,',
'.t-Body,',
'.t-Body-content,',
'.t-Body-main,',
'.t-Body-mainContent,',
'.t-Body-title,',
'.t-Body-contentInner {',
'  background: var(--inv700-bg) !important;',
'  color: var(--inv700-text) !important;',
'}',
'',
'.t-Body-content {',
'  padding-bottom: 88px !important;',
'}',
'',
'.t-Region {',
'  background: transparent !important;',
'  box-shadow: none !important;',
'  border: none !important;',
'  margin-bottom: 0 !important;',
'}',
'',
'.t-Region-header,',
'.t-Region-title {',
'  display: none !important;',
'}',
'',
'.t-Region-body,',
'.t-Region-bodyWrap {',
'  padding: 0 !important;',
'  background: transparent !important;',
'  border: none !important;',
'}',
'',
'.t-Body-mainContent {',
'  max-width: 1200px;',
'  margin: 0 auto;',
'  padding: 24px 28px 0 !important;',
'}',
'',
'/* --- Utils --- */',
'.inv700-hidden { display: none !important; }',
'',
'/* --- Header --- */',
'.inv700-kicker {',
'  font-family: ui-monospace, monospace;',
'  font-size: 12px;',
'  color: var(--inv700-text-muted);',
'  display: block;',
'}',
'',
'.inv700-title {',
'  margin: 0;',
'  font-size: 22px;',
'  font-weight: 600;',
'  color: var(--inv700-text);',
'}',
'',
'.inv700-header {',
'  display: flex;',
'  align-items: center;',
'  justify-content: space-between;',
'  gap: 16px;',
'  padding: 20px 0 16px;',
'  border-bottom: 1px solid var(--inv700-stroke);',
'  margin-bottom: 24px;',
'}',
'',
'.inv700-label {',
'  font-size: 12px;',
'  text-transform: uppercase;',
'  letter-spacing: 0.04em;',
'  color: var(--inv700-text-muted);',
'}',
'',
'.inv700-hint {',
'  margin: 0 0 12px;',
'  font-size: 12px;',
'  color: var(--inv700-text-muted);',
'}',
'',
'/* --- Search --- */',
'.inv700-search {',
'  margin-bottom: 24px;',
'}',
'',
'.inv700-search__head {',
'  display: flex;',
'  align-items: center;',
'  justify-content: space-between;',
'  gap: 12px;',
'  margin-bottom: 10px;',
'}',
'',
'.inv700-search__title {',
'  margin: 0;',
'  font-size: 13px;',
'  font-weight: 600;',
'  color: var(--inv700-text);',
'}',
'',
'.inv700-search__panel {',
'  background: var(--inv700-surface);',
'  padding: 16px 18px;',
'  border-radius: var(--inv700-radius);',
'  box-shadow: var(--inv700-shadow);',
'  border: 1px solid var(--inv700-stroke);',
'}',
'',
'.inv700-search__row {',
'  display: flex;',
'  gap: 10px;',
'  flex-wrap: wrap;',
'  align-items: center;',
'}',
'',
'.inv700-input {',
'  flex: 1;',
'  min-width: 220px;',
'  padding: 10px 12px;',
'  border-radius: 6px;',
'  border: 1px solid var(--inv700-stroke);',
'  background: var(--inv700-surface);',
'  color: var(--inv700-text);',
'  font-size: 14px;',
'}',
'',
'.inv700-input::placeholder {',
'  color: #a0a0aa;',
'}',
'',
'.inv700-input:focus {',
'  outline: none;',
'  border-color: var(--inv700-accent);',
'  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.15);',
'}',
'',
'.inv700-search__filters {',
'  display: flex;',
'  gap: 6px;',
'}',
'',
'/* --- Buttons (override violet UT) --- */',
'.inv700-btn {',
'  padding: 8px 14px;',
'  border-radius: 6px;',
'  border: 1px solid var(--inv700-stroke);',
'  background: var(--inv700-surface);',
'  color: var(--inv700-text);',
'  cursor: pointer;',
'  font-size: 13px;',
'  transition: background 0.15s ease;',
'}',
'',
'.inv700-btn:hover {',
'  background: var(--inv700-surface-alt);',
'}',
'',
'.inv700-btn--primary {',
'  background: var(--inv700-accent) !important;',
'  border-color: transparent !important;',
'  color: #fff !important;',
'}',
'',
'.inv700-btn--primary:hover {',
'  background: var(--inv700-accent-hover) !important;',
'}',
'',
'.inv700-btn--primary:disabled {',
'  opacity: 0.45;',
'  cursor: not-allowed;',
'}',
'',
'.inv700-btn--filter.is-active {',
'  background: var(--inv700-accent) !important;',
'  border-color: transparent !important;',
'  color: #fff !important;',
'}',
'',
'.inv700-btn--ghost {',
'  background: transparent;',
'}',
'',
'/* --- Pills --- */',
'.inv700-pill {',
'  padding: 6px 12px;',
'  border-radius: 999px;',
'  font-size: 12px;',
'  font-weight: 600;',
'  border: 1px solid var(--inv700-stroke);',
'}',
'',
'.inv700-pill--open {',
'  color: var(--inv700-warn);',
'  border-color: rgba(180, 83, 9, 0.35);',
'  background: rgba(180, 83, 9, 0.08);',
'}',
'',
'.inv700-pill--closing {',
'  color: var(--inv700-info);',
'  border-color: rgba(37, 99, 235, 0.35);',
'  background: rgba(37, 99, 235, 0.08);',
'}',
'',
'.inv700-pill--closed {',
'  color: var(--inv700-closed);',
'  border-color: rgba(220, 38, 38, 0.35);',
'  background: rgba(220, 38, 38, 0.08);',
'}',
'',
'/* --- Workspace : masqué tant qu''aucune recherche --- */',
'.inv700-workspace.inv700-workspace--empty {',
'  display: none !important;',
'}',
'',
'.inv700-workspace {',
'  display: grid;',
'  grid-template-columns: 1fr;',
'  gap: 0;',
'  margin-bottom: 24px;',
'  min-height: 420px;',
'  background: var(--inv700-surface);',
'  border: 1px solid var(--inv700-stroke);',
'  border-radius: var(--inv700-radius);',
'  box-shadow: var(--inv700-shadow);',
'  overflow: hidden;',
'}',
'',
'.inv700-workspace--multi {',
'  grid-template-columns: minmax(220px, 280px) 1fr;',
'}',
'',
'/* --- Lot list --- */',
'.inv700-lot-list {',
'  border-right: 1px solid var(--inv700-stroke);',
'  display: flex;',
'  flex-direction: column;',
'  max-height: 560px;',
'  background: var(--inv700-surface-alt);',
'}',
'',
'.inv700-lot-list__head {',
'  padding: 12px 14px;',
'  background: #e4e6ea;',
'  border-bottom: 1px solid var(--inv700-stroke);',
'}',
'',
'.inv700-lot-list__count {',
'  font-weight: 600;',
'  font-size: 13px;',
'  display: block;',
'}',
'',
'.inv700-lot-list__hint {',
'  font-size: 11px;',
'  color: var(--inv700-text-muted);',
'  display: block;',
'  margin-top: 2px;',
'}',
'',
'.inv700-lot-list__body {',
'  overflow-y: auto;',
'  flex: 1;',
'}',
'',
'.inv700-lot-row {',
'  display: block;',
'  width: 100%;',
'  text-align: left;',
'  padding: 10px 12px;',
'  border: none;',
'  border-bottom: 1px solid var(--inv700-stroke);',
'  border-left: 3px solid transparent;',
'  background: transparent;',
'  color: var(--inv700-text);',
'  cursor: pointer;',
'}',
'',
'.inv700-lot-row:hover {',
'  background: rgba(0, 0, 0, 0.03);',
'}',
'',
'.inv700-lot-row.is-selected {',
'  background: rgba(37, 99, 235, 0.08);',
'  border-left-color: var(--inv700-accent);',
'}',
'',
'.inv700-lot-row__top {',
'  display: flex;',
'  justify-content: space-between;',
'  align-items: center;',
'  gap: 8px;',
'}',
'',
'.inv700-lot-row__no {',
'  font-family: ui-monospace, monospace;',
'  font-size: 13px;',
'  font-weight: 600;',
'}',
'',
'.inv700-lot-row__status {',
'  font-family: ui-monospace, monospace;',
'  font-size: 11px;',
'}',
'',
'.inv700-lot-row__status--sc { color: var(--inv700-warn); }',
'.inv700-lot-row__status--ok { color: var(--inv700-closed); }',
'',
'.inv700-lot-row__sub {',
'  font-size: 11px;',
'  color: var(--inv700-text-muted);',
'  margin-top: 4px;',
'}',
'',
'.inv700-detail__empty {',
'  padding: 48px 24px;',
'  text-align: center;',
'  color: var(--inv700-text-muted);',
'}',
'',
'/* --- Hero + metrics --- */',
'.inv700-lot-grid {',
'  display: grid;',
'  grid-template-columns: 1fr 1fr;',
'  border-bottom: 1px solid var(--inv700-stroke);',
'}',
'',
'.inv700-lot-hero {',
'  position: relative;',
'  padding: 24px 22px;',
'  border-right: 1px solid var(--inv700-stroke);',
'  overflow: hidden;',
'  min-height: 280px;',
'  background: var(--inv700-surface);',
'}',
'',
'.inv700-lot-hero.is-closed {',
'  animation: inv700-flash 1s ease;',
'}',
'',
'@keyframes inv700-flash {',
'  from { background: rgba(220, 38, 38, 0.08); }',
'  to   { background: var(--inv700-surface); }',
'}',
'',
'.inv700-stamp {',
'  position: absolute;',
'  top: 16px;',
'  right: 16px;',
'  padding: 7px 14px;',
'  border: 2px solid var(--inv700-closed);',
'  color: var(--inv700-closed);',
'  font-family: ui-monospace, monospace;',
'  font-size: 13px;',
'  font-weight: 600;',
'  letter-spacing: 0.2em;',
'  transform: rotate(-3deg);',
'  z-index: 2;',
'}',
'',
'.inv700-lot-no {',
'  font-family: ui-monospace, monospace;',
'  font-size: 28px;',
'  font-weight: 700;',
'  display: block;',
'}',
'',
'.inv700-lot-id {',
'  font-size: 12px;',
'  color: var(--inv700-text-muted);',
'}',
'',
'.inv700-dl,',
'.inv700-metrics__grid {',
'  display: grid;',
'  grid-template-columns: 1fr 1fr;',
'  gap: 16px;',
'  margin: 16px 0 0;',
'}',
'',
'.inv700-dl dt,',
'.inv700-metrics__grid dt {',
'  font-size: 11px;',
'  color: var(--inv700-text-muted);',
'  margin-bottom: 2px;',
'}',
'',
'.inv700-dl dd,',
'.inv700-metrics__grid dd {',
'  margin: 0;',
'  font-weight: 500;',
'  font-family: ui-monospace, monospace;',
'  font-size: 14px;',
'}',
'',
'.inv700-metrics {',
'  padding: 24px 22px;',
'  background: var(--inv700-surface-alt);',
'}',
'',
'.inv700-metrics__grid dd {',
'  font-size: 22px;',
'  font-weight: 700;',
'}',
'',
'/* --- Impact --- */',
'.inv700-impact {',
'  padding: 18px 18px 22px;',
'  background: var(--inv700-surface);',
'}',
'',
'.inv700-impact__head {',
'  display: flex;',
'  align-items: center;',
'  justify-content: space-between;',
'  gap: 12px;',
'  margin-bottom: 8px;',
'}',
'',
'.inv700-impact__title {',
'  margin: 0;',
'  font-size: 13px;',
'  font-weight: 600;',
'}',
'',
'.inv700-impact__summary {',
'  font-size: 12px;',
'  color: var(--inv700-text-muted);',
'}',
'',
'.inv700-progress {',
'  height: 3px;',
'  background: var(--inv700-surface-alt);',
'  margin: 14px 0 16px;',
'  overflow: hidden;',
'  border-radius: 2px;',
'}',
'',
'.inv700-progress__bar {',
'  height: 100%;',
'  width: 0;',
'  background: var(--inv700-accent);',
'  transition: width 0.4s ease;',
'}',
'',
'.inv700-progress__bar.is-closed {',
'  background: var(--inv700-closed);',
'}',
'',
'.inv700-impact-list {',
'  list-style: none;',
'  margin: 0;',
'  padding: 0;',
'  display: flex;',
'  gap: 16px;',
'  flex-wrap: wrap;',
'}',
'',
'.inv700-impact-item {',
'  flex: 1 1 120px;',
'  opacity: 0.55;',
'}',
'',
'.inv700-impact-item.is-done {',
'  opacity: 1;',
'}',
'',
'.inv700-impact-item__dot {',
'  width: 8px;',
'  height: 8px;',
'  border-radius: 50%;',
'  background: #c8cad0;',
'  margin-bottom: 6px;',
'}',
'',
'.inv700-impact-item.is-done .inv700-impact-item__dot {',
'  background: var(--inv700-closed);',
'}',
'',
'.inv700-impact-item__label {',
'  font-size: 13px;',
'  font-weight: 600;',
'  display: block;',
'}',
'',
'.inv700-impact-item__sub {',
'  font-size: 11px;',
'  color: var(--inv700-text-muted);',
'}',
'',
'.inv700-impact-item__done {',
'  font-size: 11px;',
'  color: var(--inv700-closed);',
'  margin-top: 4px;',
'}',
'',
'/* --- Action bar --- */',
'.inv700-action-bar {',
'  position: fixed;',
'  left: 0;',
'  right: 0;',
'  bottom: 0;',
'  z-index: 500;',
'  display: flex;',
'  align-items: center;',
'  gap: 16px;',
'  padding: 14px 28px;',
'  background: rgba(255, 255, 255, 0.96);',
'  border-top: 1px solid var(--inv700-stroke);',
'  backdrop-filter: blur(8px);',
'  box-shadow: 0 -4px 16px rgba(0, 0, 0, 0.06);',
'}',
'',
'.inv700-action-bar__lot {',
'  font-family: ui-monospace, monospace;',
'  font-size: 14px;',
'}',
'',
'.inv700-action-bar__msg {',
'  font-size: 12px;',
'  color: var(--inv700-text-muted);',
'  flex: 1;',
'}',
'',
'.inv700-action-bar__buttons {',
'  display: flex;',
'  gap: 10px;',
'  margin-left: auto;',
'}',
'',
'@media (max-width: 768px) {',
'  .t-Body-mainContent { padding: 16px !important; }',
'  .inv700-workspace--multi { grid-template-columns: 1fr; }',
'  .inv700-lot-list {',
'    max-height: 220px;',
'    border-right: none;',
'    border-bottom: 1px solid var(--inv700-stroke);',
'  }',
'  .inv700-lot-grid { grid-template-columns: 1fr; }',
'  .inv700-lot-hero {',
'    border-right: none;',
'    border-bottom: 1px solid var(--inv700-stroke);',
'  }',
'  .inv700-action-bar { flex-wrap: wrap; padding: 12px 16px; }',
'}',
''
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'17'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11719866209193524)
,p_plug_name=>unistr('Hidden Items \2014 Search, filter & selected lot state')
,p_region_name=>'RGN_P51_HIDDEN_PAGE_ITEMS'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(23100796682588931)
,p_plug_display_sequence=>10
,p_location=>null
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11719986758193525)
,p_plug_name=>unistr('Page Header \2014 Close SPIN-LOT title & status')
,p_region_name=>'RGN_P51_PAGE_HEADER'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(23091006266588914)
,p_plug_display_sequence=>20
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="inv700-header">',
'  <div class="inv700-header__titles">',
'    <span class="inv700-kicker">SC-INV700</span>',
'    <h1 class="inv700-title">Close SPIN-LOT</h1>',
'  </div>',
'  <span id="inv700-status" class="inv700-pill inv700-pill--hidden" aria-live="polite"></span>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11720042098193526)
,p_plug_name=>unistr('Lot Search \2014 Find lot & Open/All filter')
,p_region_name=>'RGN_P51_LOT_SEARCH_PANEL'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(23091006266588914)
,p_plug_display_sequence=>30
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div class="inv700-search">',
'  <div class="inv700-search__head">',
'    <h2 class="inv700-search__title">Find lot</h2>',
'    <div class="inv700-search__filters">',
'      <button type="button" id="inv700-filter-open" class="inv700-btn inv700-btn--filter is-active" data-filter="OPEN">Open</button>',
'      <button type="button" id="inv700-filter-all" class="inv700-btn inv700-btn--filter" data-filter="ALL">All</button>',
'    </div>',
'  </div>',
'  <div class="inv700-search__panel">',
unistr('    <p class="inv700-hint">LOT#, WKS ORDER, PRODUCT, YARN-FLG, or MCODE \2014 try <strong style="font-family:monospace">2608</strong> for multiple lots</p>'),
'    <div class="inv700-search__row">',
'      <input type="text" id="P51_SEARCH" class="inv700-input" placeholder="e.g. 2608, 2608-0027, 1F" autocomplete="off" />',
'      <button type="button" id="inv700-btn-load" class="inv700-btn inv700-btn--primary">Load lot</button>',
'    </div>',
'  </div>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11720110472193527)
,p_plug_name=>unistr('Master-Detail \2014 Lot list, lot detail & closing impact')
,p_region_name=>'RGN_P51_MASTER_DETAIL_WORKSPACE'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(23091006266588914)
,p_plug_display_sequence=>40
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div id="inv700-workspace" class="inv700-workspace inv700-workspace--empty">',
'  <aside id="inv700-lot-list" class="inv700-lot-list" aria-label="Matching lots">',
'    <div class="inv700-lot-list__head">',
'      <span id="inv700-lot-count" class="inv700-lot-list__count">0 lots</span>',
unistr('      <span class="inv700-lot-list__hint">Click to preview \2014 close one at a time</span>'),
'    </div>',
'    <div id="inv700-lot-list-body" class="inv700-lot-list__body"></div>',
'  </aside>',
'',
'  <main id="inv700-detail" class="inv700-detail">',
'    <div id="inv700-detail-empty" class="inv700-detail__empty">',
'      <p>Select a lot from the list or search above.</p>',
'    </div>',
'',
'    <div id="inv700-detail-content" class="inv700-detail__content inv700-hidden">',
'      <div class="inv700-lot-grid">',
'        <section class="inv700-lot-hero" id="inv700-lot-hero">',
'          <div id="inv700-stamp" class="inv700-stamp inv700-hidden">CLOSED!!</div>',
'          <div class="inv700-lot-hero__meta">',
'            <span class="inv700-label">Main spin lot</span>',
'            <span id="inv700-lot-no" class="inv700-lot-no"></span>',
'            <span id="inv700-lot-id" class="inv700-lot-id"></span>',
'          </div>',
'          <dl class="inv700-dl">',
'            <div><dt>Product</dt><dd id="inv700-product"></dd></div>',
'            <div><dt>Yarn flag</dt><dd id="inv700-yarn"></dd></div>',
'            <div><dt>MCODE</dt><dd id="inv700-mcode"></dd></div>',
'            <div><dt>Sched date</dt><dd id="inv700-date-sch"></dd></div>',
'          </dl>',
'        </section>',
'        <section class="inv700-metrics">',
'          <span class="inv700-label">Quantities</span>',
'          <dl class="inv700-metrics__grid">',
'            <div><dt>Qty ordered</dt><dd id="inv700-qty-ord"></dd></div>',
'            <div><dt>Qty received</dt><dd id="inv700-qty-rec"></dd></div>',
'            <div><dt>Qty on hand</dt><dd id="inv700-qoh"></dd></div>',
'            <div><dt>Blend wt</dt><dd id="inv700-kgs1"></dd></div>',
'            <div><dt>Card wt</dt><dd id="inv700-kgs2"></dd></div>',
'          </dl>',
'        </section>',
'      </div>',
'',
'      <section class="inv700-impact">',
'        <div class="inv700-impact__head">',
'          <h2 class="inv700-impact__title">Closing impact</h2>',
'          <span id="inv700-impact-summary" class="inv700-impact__summary"></span>',
'        </div>',
'        <p class="inv700-hint">Review what will be closed before confirming.</p>',
'        <div id="inv700-progress" class="inv700-progress inv700-hidden">',
'          <div id="inv700-progress-bar" class="inv700-progress__bar"></div>',
'        </div>',
'        <ul id="inv700-impact-list" class="inv700-impact-list"></ul>',
'      </section>',
'    </div>',
'  </main>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(11720230579193528)
,p_plug_name=>unistr('Action Bar \2014 Close SPIN-LOT confirmation')
,p_region_name=>'RGN_P51_CLOSE_ACTION_BAR'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>wwv_flow_imp.id(23091006266588914)
,p_plug_display_sequence=>50
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<div id="inv700-action-bar" class="inv700-action-bar inv700-hidden">',
'  <span id="inv700-action-lot" class="inv700-action-bar__lot"></span>',
'  <span id="inv700-action-msg" class="inv700-action-bar__msg"></span>',
'  <div class="inv700-action-bar__buttons">',
'    <button type="button" id="inv700-btn-clear" class="inv700-btn inv700-btn--ghost">Clear selection</button>',
'    <button type="button" id="inv700-btn-close" class="inv700-btn inv700-btn--primary" disabled>Close SPIN-LOT</button>',
'  </div>',
'</div>'))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(11720486166193530)
,p_name=>'P51_FILTER'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(11719866209193524)
,p_item_default=>'OPEN'
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(11720587579193531)
,p_name=>'P51_LOT_ID'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_imp.id(11719866209193524)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(11720610558193532)
,p_name=>'P51_WORKS_ORDER'
,p_item_sequence=>40
,p_item_plug_id=>wwv_flow_imp.id(11719866209193524)
,p_display_as=>'NATIVE_HIDDEN'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'value_protected', 'N')).to_clob
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(11720754856193533)
,p_process_sequence=>10
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'SEARCH_LOTS'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_search VARCHAR2(100) := apex_application.g_x01;',
'  l_filter VARCHAR2(10)  := UPPER(NVL(apex_application.g_x02, ''OPEN''));',
'BEGIN',
'  apex_json.open_object;',
'  apex_json.open_array(''lots'');',
'  FOR r IN (',
'    SELECT TRIM(p.lot_no) AS works_order, p.lot_id,',
'           TRIM(p.yarn_flg) AS yarn_flg, TRIM(p.mcode) AS mcode,',
'           TO_CHAR(p.date_sch, ''DD-MON-YY'') AS date_sch,',
'           CASE WHEN TRIM(p.status) IN (''OK'', ''DD'') THEN 1 ELSE 0 END AS is_closed',
'      FROM wool.prod_lot p',
'     WHERE TRIM(p.works_order) = TRIM(p.lot_no)',
'       AND (l_filter = ''ALL'' OR TRIM(p.status) NOT IN (''OK'', ''DD''))',
'       AND (',
'            l_search IS NULL OR TRIM(l_search) IS NULL',
'            OR UPPER(TRIM(p.lot_no))      LIKE ''%'' || UPPER(TRIM(l_search)) || ''%''',
'            OR UPPER(TRIM(p.product_no)) LIKE ''%'' || UPPER(TRIM(l_search)) || ''%''',
'            OR UPPER(TRIM(p.yarn_flg))  LIKE ''%'' || UPPER(TRIM(l_search)) || ''%''',
'            OR UPPER(TRIM(p.mcode))      LIKE ''%'' || UPPER(TRIM(l_search)) || ''%''',
'           )',
'     ORDER BY p.lot_id DESC',
'     FETCH FIRST 50 ROWS ONLY',
'  ) LOOP',
'    apex_json.open_object;',
'    apex_json.write(''worksOrder'', r.works_order);',
'    apex_json.write(''lotId'', r.lot_id);',
'    apex_json.write(''yarnFlg'', r.yarn_flg);',
'    apex_json.write(''mcode'', r.mcode);',
'    apex_json.write(''dateSch'', r.date_sch);',
'    apex_json.write(''isClosed'', r.is_closed = 1);',
'    apex_json.close_object;',
'  END LOOP;',
'  apex_json.close_array;',
'  apex_json.close_object;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.open_object;',
'    apex_json.write(''success'', false);',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.open_array(''lots'');',
'    apex_json.close_array;',
'    apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>11720754856193533
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(11720899599193534)
,p_process_sequence=>20
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'LOAD_LOT'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_wo   VARCHAR2(30) := TRIM(apex_application.g_x01);',
'  l_rec  fsm.sct_prd.t_spin_lot_rec;',
'  l_wo_t VARCHAR2(30);',
'  l_cnt  NUMBER;',
'BEGIN',
'  fsm.sct_prd.load_main_spin_lot(l_wo, l_rec);',
'',
'  IF l_rec.lot_id IS NULL THEN',
'    apex_json.open_object;',
'    apex_json.write(''success'', false);',
'    apex_json.write(''message'', ''Lot not found or not a main spin lot.'');',
'    apex_json.close_object;',
'    RETURN;',
'  END IF;',
'',
'  l_wo_t := TRIM(l_rec.lot_no);',
'',
'  apex_json.open_object;',
'  apex_json.open_object(''lot'');',
'  apex_json.write(''lotId'', l_rec.lot_id);',
'  apex_json.write(''lotNo'', TRIM(l_rec.lot_no));',
'  apex_json.write(''productNo'', TRIM(l_rec.product_no));',
'  apex_json.write(''yarnFlg'', TRIM(l_rec.yarn_flg));',
'  apex_json.write(''mcode'', TRIM(l_rec.mcode));',
'  apex_json.write(''dateSch'', TO_CHAR(l_rec.date_sch, ''DD-MON-YY''));',
'  apex_json.write(''qtyOrd'', l_rec.qty_ord);',
'  apex_json.write(''qtyRec'', l_rec.qty_rec);',
'  apex_json.write(''qoh'', l_rec.qoh);',
'  apex_json.write(''kgs1'', l_rec.input_wt);',
'  apex_json.write(''kgs2'', NULL);',
'  apex_json.write(''isClosed'', UPPER(TRIM(l_rec.status)) IN (''OK'', ''DD''));',
'  apex_json.close_object;',
'',
'  apex_json.open_array(''impact'');',
'',
'  apex_json.open_object;',
'  apex_json.write(''id'', ''spin'');',
'  apex_json.write(''label'', ''Spin lot'');',
'  apex_json.write(''count'', 1);',
'  apex_json.close_object;',
'',
'  SELECT COUNT(*) INTO l_cnt FROM wool.wip_hdr',
'   WHERE TRIM(works_order) = l_wo_t AND TRIM(status) NOT IN (''OK'');',
'  IF l_cnt > 0 THEN',
'    apex_json.open_object;',
'    apex_json.write(''id'', ''wip'');',
'    apex_json.write(''label'', ''Work in progress'');',
'    apex_json.write(''count'', l_cnt);',
'    apex_json.close_object;',
'  END IF;',
'',
'  SELECT COUNT(*) INTO l_cnt FROM wool.d_blendhdr',
'   WHERE TRIM(works_order) = l_wo_t AND TRIM(status) NOT IN (''OK'');',
'  IF l_cnt > 0 THEN',
'    apex_json.open_object;',
'    apex_json.write(''id'', ''blend'');',
'    apex_json.write(''label'', ''Blend orders'');',
'    apex_json.write(''count'', l_cnt);',
'    apex_json.close_object;',
'  END IF;',
'',
'  SELECT COUNT(*) INTO l_cnt FROM wool.ord_ship',
'   WHERE TRIM(lot_no) = l_wo_t AND TRIM(status) NOT IN (''OK'');',
'  IF l_cnt > 0 THEN',
'    apex_json.open_object;',
'    apex_json.write(''id'', ''ship'');',
'    apex_json.write(''label'', ''Shipment'');',
'    apex_json.write(''count'', l_cnt);',
'    apex_json.close_object;',
'  END IF;',
'',
'  SELECT COUNT(*) INTO l_cnt FROM wool.prod_lot',
'   WHERE TRIM(works_order) = l_wo_t',
'     AND TRIM(lot_no) <> l_wo_t',
'     AND TRIM(status) NOT IN (''OK'', ''DD'');',
'  IF l_cnt > 0 THEN',
'    apex_json.open_object;',
'    apex_json.write(''id'', ''linked'');',
'    apex_json.write(''label'', ''Related lots'');',
'    apex_json.write(''count'', l_cnt);',
'    apex_json.close_object;',
'  END IF;',
'',
'  apex_json.close_array;',
'  apex_json.close_object;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.open_object;',
'    apex_json.write(''success'', false);',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>11720899599193534
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(11720959277193535)
,p_process_sequence=>30
,p_process_point=>'ON_DEMAND'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'CLOSE_LOT'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'  l_lot_id NUMBER := TO_NUMBER(apex_application.g_x01);',
'BEGIN',
'  fsm.sct_prd.close_spin_lot_inv700(l_lot_id);',
'',
'  apex_json.open_object;',
'  apex_json.write(''success'', true);',
'  apex_json.write(''message'', ''SPIN-LOT closed successfully.'');',
'  apex_json.close_object;',
'EXCEPTION',
'  WHEN OTHERS THEN',
'    apex_json.open_object;',
'    apex_json.write(''success'', false);',
'    apex_json.write(''message'', SQLERRM);',
'    apex_json.close_object;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_internal_uid=>11720959277193535
);
end;
/
prompt --application/end_environment
begin
wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false)
);
commit;
end;
/
set verify on feedback on define on
prompt  ...done
